apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.3.0
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql  # Répertoire où MySQL stocke ses données
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvcc  # Doit correspondre au PVC
