apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvcc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard  # Replace "standard" with a resize-capable StorageClass in your cluster
