apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mysql-storage-class
  hostPath:
    path: "/mnt/data/mysql"
