apiVersion: v1
kind: Service
metadata:
  name: tp-foyer
  namespace: prod
spec:
  type: NodePort
  selector:
    app: tp-foyer
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
      nodePort: 31874
