apiVersion: v1
kind: Service
metadata:
  name: angular-app
  namespace: prod
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 80
      nodePort: 30085
